# Generated by Django 6.0.2 on 2026-02-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/'),
        ),
    ]
