# Generated by Django 6.0.2 on 2026-02-18 02:15

import futsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_facility_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsalinfo',
            name='google_map_link',
            field=models.URLField(blank=True, validators=[futsal.models.validate_google_map_embed_url]),
        ),
    ]
